version: 0.2
env: 
  parameter-store: 
    MONGO: "/abhishek/mongo"
phases:
  pre_build:
    commands:
       - echo Build Started on `date`
  build:
    commands:
       - sed -i 's/process.env.MONGODB_URI/'$MONGO'/' app.js
       - npm install
  post_build:
    commands:
       - echo Build Completed on `date`

artifacts:
  files:
    - '**/*'
